### ISSUE TITLE
Will it support QMK eventually ?

### ISSUE THREAD

**Issue by harshitgoel96** [wez/SpockKeyboard#1]
Hi @wez 

I love the design of the keyboard. It looks like it is currently running a very basic firmware. I just want to know if it would ever run QMK ?

**Comment by wez** [comment]
It shouldn't be especially difficult to get QMK running for this board.  I didn't start with QMK because QMK is still reasonably AVR centric and the controller I'm using didn't have great support last time I checked.  The hardest part is the matrix/keymap stuff, but that is already basically there as the KEYMAP macro I've used here is deliberately similar to the QMK style.

However, I don't have immediate plans to port QMK to this board myself.

**Comment by harshitgoel96** [comment]
Feather 32u4 is supported by QMK out of the box. So I am assuming you are using M0 variant of feather. well its a nice layout, I might build one eventually as the ergodox I have is not for my hand. I have long fingers but short thumb. so this results in very bad thumb cluster reach.

**Comment by wez** [comment]
I just pushed support for QMK to my own qmk fork; see the commit referenced above!
